### PR TITLE
Make the color% class implement the equal<%> interface

### PR DESCRIPTION
**Pull request by joergen7**
This extension enables comparing color% objects. We define colors as equal when they have the same red, green, blue, and alpha value. Mutable and immutable instances of the same color are equal.

### CODE REVIEW

**Comment by pmatos** [comment]
Nice. I guess someone like @mflatt will have to review and merge.

**Comment by samth** [comment]
I think the tests should probably go in https://github.com/racket/draw/tree/master/draw-test/tests/racket/draw. Otherwise, this looks good.

**Comment by joergen7** [comment]
I have moved the unit tests out of `draw-lib/racket/draw/private/color.rkt` and into a new file `draw-test/tests/racket/draw/color.rkt`. I have checked if everything works by running `raco test draw-test`.

**Comment by samth** [comment]
This looks good to me, but I'd like @mflatt's opinion.

**Comment by gus-massa** [comment]
I think this is a good idea (and it would be nice to expand it later to other similar things), but it must be explained in the documentation.

---

An additional technical question: After this change `(make-color 1 2 3 4)` will collide in the hash tables with `(list 1 2 3 4)`, IIUC.

Is it a good idea to add some random thing to reduce collisions? Something like 

        (define/public (equal-secondary-hash-code-of hash-code)
          (hash-code (list 'my-secret-thing-for-colors r g b a)))))

Should `equal-secondary-hash-code-of` use `secondary-hash-code` instead of `hash-code`?

**Comment by joergen7** [comment]
Hello @gus-massa, as suggested, I have added a section to the draw documentation that explains equality for `color%` instances. Also, I have included a random symbol in both methods `equal-hash-code-of` and `equal-secondary-hash-code-of`. As a result, the result of both functions should differ even if the `hash-code` argument is the same hash function.

**Comment by samth** [comment]
ping @mflatt

**Comment by gus-massa** [comment]
I'm not sure if adding a random symbol is necessary. (Sorry if my question looked like an informed question.) I guess we must wait @mflatt opinion. 

And I have more questions: Is it better/necessary to use the same symbol? Is a number better? Is better to use `equal-secondary-hash-code` in the second one?

**Comment by joergen7** [comment]
Hello @gus-massa, I find your hint at the hash generation helpful and, when I originally created the pr, I had similar thoughts. I made the original pr intentionally simplistic because I felt it would increase the chance of the pr to be accepted.

In response to your hint, I inserted a random symbol because I assume, that generating a hash of a symbol is cheap but I could be wrong. The symbol also removes the possibility of hash collisions between `color%`'s primary and secondary hash and a list of color values (+alpha value).

**Review by mflatt — CHANGES_REQUESTED** [review]
Sorry for the very long delay here!

I think the note on equality would be better in "color-class.scrbl" (as the second paragraph there) instead of "guide.scrbl". Otherwise, I'd say this is definitely ready to merge.

**Comment by joergen7** [comment]
Hi @mflatt, I have moved the paragraph to the color-class documentation.

**Comment by mflatt** [comment]
Thanks!

**Pull request merged**
